---
AWSTemplateFormatVersion: "2010-09-09"
Description: ffxiv-item-name-database-prepare

Parameters:
  SAMDeployUserName:
    Type: String
    Default: sam-deploy-user

Resources:
  SAMDeployUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref SAMDeployUserName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: CloudFormationDeployPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - iam:PassRole
                Resource:
                  - "*"

  CloudFormationDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  SAMArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 7
            Status: Enabled

Outputs:
  SAMArtifactBucketName:
    Value: !Ref SAMArtifactBucket

  CloudFormationDeployRoleArn:
    Value: !GetAtt CloudFormationDeployRole.Arn